export const INPUT_FOCUS = 'header/INPUT_FOCUS'
export const INPUT_BLUR = 'header/INPUT_BLUR'
export const SEARCH_POPULAR_LIST = 'header/SEARCH_POPULAR_LIST'
export const MOUSE_ENTER = 'header/MOUSE_ENTER'
export const MOUSE_LEAVE = 'header/MOUSE_LEAVE'
export const CHANGE_PAGE = 'header/CHANGE_PAGE'